timezone: "America/New_York"
description: "Software engineer, open web enthusiast, essayist, privacy and encryption advocate. Idealist. Recovering techno-utopian."
paginate: 10
permalink: pretty
sass:
  style: compressed

exclude: [
  CNAME,
  LICENSE,
  README.md
]

plugins:
  - jekyll-feed
  - jekyll-sitemap

