# Site settings
name: 0xADADA
description: Homepage of 0xADADA
url: https://0xadada.pub

# Build settings
markdown: kramdown
paginate: 10
permalink: pretty

# Project settings
exclude: [
  Gemfile,
  Gemfile.lock,
  node_modules,
  LICENSE,
  README.md
]
