# Site settings
name: "0xADADA"
description: "Writing of 0xADADA"
url: "https://0xadada.pub"
author: "0xADADA"

# Build settings
markdown: kramdown
paginate: 10
permalink: pretty
sass:
  style: compressed

# Jekyll plugins
gems:
  - jekyll-feed
  - jekyll-sitemap

# Project settings
exclude: [
  Gemfile,
  Gemfile.lock,
  node_modules,
  LICENSE,
  README.md
]
