import Link from "next/link";
import Head from "next/head";
import styles from "./layout.module.css";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="home" href="https://0xadada.pub/" />
        <link
          rel="sitemap"
          type="application/xml"
          href="https://0xadada.pub/sitemap.xml"
          title="Sitemap"
        />
        <link rel="manifest" href="/static/images/meta/0xadada.webmanifest" />
        <link
          rel="apple-touch-icon"
          href="/static/images/meta/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          href="/static/images/meta/favicon-32x32.png"
          sizes="32x32"
        />
        <link
          rel="icon"
          type="image/png"
          href="/static/images/meta/favicon-16x16.png"
          sizes="16x16"
        />
        <link
          rel="mask-icon"
          href="/static/images/meta/safari-pinned-tab.svg"
          color="#5bbad5"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="msapplication-config"
          content="/static/images/meta/browserconfig.xml"
        />
        <meta name="theme-color" content="#FDF9F0" />
        <meta
          name="pocket-site-verification"
          content="7431f135e23a84de547e5b79dab406"
        />
      </Head>
      <header>
        <p>header</p>
      </header>
      <main>{children}</main>
    </>
  );
};

export default Layout;
