import Link from "next/link";
import Head from "next/head";
import styles from "./layout.module.css";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <p>header</p>
      </header>
      <main>{children}</main>
    </>
  );
};

export default Layout;
